# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 29ca32c379b850d05ce14091e7094fd05d741601c9b43e1b7345f92bcec7129e5bb15ee7266f95b933b0ef5e238cfaadbf74522a5c327d0fbbe935813006adbd

test:
  secret_key_base: b5985a02a86033f89adc0987210648596d1bcb5368e56ae2054f533b885238767668163c324781ca609425907dc6990e4034981a5ca356e0e8dce356473c219d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
